import { isSpecialPage } from "../check/util.ts";
import { isSharedRootFolder } from "../check/placement-table.ts";
import type { Page, Vault } from "./types.ts";

/** The first line of every generated index file; the gate compares whole files, so it is part of the output. */
export const GENERATED_NOTE = "%% Generated by `cf index`. Never edit by hand. %%";

/** One `##` section of a Campaign folder's index. `kinds` splits a section into `###` sub-groups, in order. */
interface Section {
	heading: string;
	type: string;
	kinds?: { kind: string; heading: string }[];
}

/**
 * The fixed order of a Campaign folder's index: World kinds, then Campaign kinds, then Session kinds
 * (the order of the tree in `docs/wiki-layout.md`). Pages that fit no section end up under `## Other`.
 * The Campaign overview is the index heading itself, so it has no section.
 */
const SECTIONS: Section[] = [
	{
		heading: "Locations",
		type: "Location",
		kinds: [
			{ kind: "Region", heading: "Regions" },
			{ kind: "Settlement", heading: "Settlements" },
			{ kind: "Site", heading: "Sites" },
		],
	},
	{ heading: "NPCs", type: "NPC" },
	{ heading: "Creatures", type: "Creature" },
	{ heading: "Factions", type: "Faction" },
	{ heading: "Deities", type: "Deity" },
	{ heading: "Items", type: "Item" },
	{ heading: "Spells", type: "Spell" },
	{ heading: "Vehicles", type: "Vehicle" },
	{ heading: "Lore", type: "Lore" },
	{ heading: "House Rules", type: "House Rule" },
	{ heading: "Worlds", type: "World" },
	{ heading: "Campaign config", type: "campaign-config" },
	{ heading: "Story so far", type: "story-so-far" },
	{ heading: "PCs", type: "PC" },
	{ heading: "Threads", type: "Thread" },
	{ heading: "Quests", type: "Quest" },
	{ heading: "Preps", type: "Prep" },
	{ heading: "Scenes", type: "Scene" },
	{ heading: "Recaps", type: "Recap" },
	{ heading: "Previously On", type: "Previously On" },
	{ heading: "Handouts", type: "Handout" },
];

const OTHER = "Other";

/** Compares names by code unit, with runs of digits compared as numbers: `Session 2` before `Session 10`, whatever the locale. */
export function compareNames(a: string, b: string): number {
	const pa = a.split(/(\d+)/);
	const pb = b.split(/(\d+)/);
	for (let i = 0; i < Math.min(pa.length, pb.length); i++) {
		const x = pa[i]!;
		const y = pb[i]!;
		if (i % 2 === 1) {
			const d = BigInt(x) - BigInt(y);
			if (d !== 0n) return d < 0n ? -1 : 1;
			if (x.length !== y.length) return x.length < y.length ? -1 : 1;
		} else if (x !== y) {
			return x < y ? -1 : 1;
		}
	}
	return pa.length - pb.length;
}

const compareByName = (a: Page, b: Page): number => compareNames(a.name, b.name) || (a.path < b.path ? -1 : a.path > b.path ? 1 : 0);

/** A canonical `[[slug|Title]]` and optional summary, flattened to one line. */
function line(page: Page): string {
	const summary = typeof page.frontmatter?.summary === "string" ? page.frontmatter.summary.replace(/\s+/g, " ").trim() : "";
	return summary === "" ? `- [[${page.slug}|${page.name}]]` : `- [[${page.slug}|${page.name}]] — ${summary}`;
}

const segmentsOf = (page: Page): string[] => page.path.split("/").slice(0, -1);
const isHot = (page: Page): boolean => page.slug === "hot";

/** Where a page sits in an index: its section, and its `###` sub-group when the section has one. */
function place(page: Page): { section: string; sub?: string } {
	const type = page.frontmatter?.type;
	const section = SECTIONS.find((s) => s.type === type);
	if (!section) return { section: OTHER };
	if (!section.kinds) return { section: section.heading };
	const kind = section.kinds.find((k) => k.kind === page.frontmatter?.kind);
	return kind ? { section: section.heading, sub: kind.heading } : { section: OTHER };
}

/** Sections and sub-groups in their fixed order, `Other` last. */
const SECTION_ORDER = [...SECTIONS.map((s) => s.heading), OTHER];
const SUB_ORDER = SECTIONS.flatMap((s) => s.kinds?.map((k) => k.heading) ?? []);

/** The whole body of an index below its title: sections in their fixed order, each page as one line. */
function indexBody(pages: Page[]): string[] {
	const groups = new Map<string, Map<string, Page[]>>();
	for (const page of pages) {
		const { section, sub = "" } = place(page);
		const subs = groups.get(section) ?? new Map<string, Page[]>();
		subs.set(sub, [...(subs.get(sub) ?? []), page]);
		groups.set(section, subs);
	}
	const blocks: string[] = [];
	for (const section of SECTION_ORDER) {
		const subs = groups.get(section);
		if (!subs) continue;
		blocks.push(`## ${section}`);
		for (const sub of [...subs.keys()].sort((a, b) => SUB_ORDER.indexOf(a) - SUB_ORDER.indexOf(b))) {
			if (sub !== "") blocks.push(`### ${sub}`);
			blocks.push(subs.get(sub)!.sort(compareByName).map(line).join("\n"));
		}
	}
	return blocks;
}

/** A Campaign overview: a `type: Campaign` page directly in its top-level Campaign folder. */
export function campaignOverviews(vault: Vault): Page[] {
	return vault.pages
		.filter((p) => {
			const segments = segmentsOf(p);
			return segments.length === 1 && !isSharedRootFolder(segments[0]!) && p.frontmatter?.type === "Campaign";
		})
		.sort(compareByName);
}

/** Each Campaign's names — its overview page answers to these (`title`, aliases, slug); `--campaign` takes any of them — mapped to its Campaign folder. */
export function campaignFolders(vault: Vault): Map<string, string> {
	const folders = new Map<string, string>();
	for (const overview of campaignOverviews(vault)) {
		const folder = segmentsOf(overview)[0]!;
		for (const name of overview.names) if (!folders.has(name)) folders.set(name, folder);
	}
	return folders;
}

/** The Campaigns by name, one per overview: what `--campaign` lists. */
export function campaignNames(vault: Vault): string[] {
	return campaignOverviews(vault).map((p) => p.name);
}

/**
 * Every generated index the vault should hold, as vault-relative path to full file text: the root
 * `index.md` listing each Campaign overview and then any shared pages by kind, and a
 * `<Campaign folder>/index.md` cataloguing that folder. Pure and deterministic.
 */
export function generateIndexes(vault: Vault): Map<string, string> {
	const out = new Map<string, string>();
	const overviews = campaignOverviews(vault);
	for (const overview of overviews) {
		const folder = segmentsOf(overview)[0]!;
		const pages = vault.pages.filter((p) => segmentsOf(p)[0] === folder && p !== overview && !isSpecialPage(p) && !isHot(p));
		out.set(`${folder}/index.md`, [GENERATED_NOTE, `# ${overview.name}`, ...indexBody(pages)].join("\n\n") + "\n");
	}
	const shared = vault.pages.filter((p) => {
		const segments = segmentsOf(p);
		return segments.length === 1 && isSharedRootFolder(segments[0]!) && !isSpecialPage(p) && !isHot(p);
	});
	const rootBlocks = [GENERATED_NOTE, "# Wiki"];
	if (overviews.length > 0) rootBlocks.push(overviews.map(line).join("\n"));
	rootBlocks.push(...indexBody(shared));
	out.set("index.md", `${rootBlocks.join("\n\n")}\n`);
	return new Map([...out].sort((a, b) => (a[0] < b[0] ? -1 : 1)));
}
