import { readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { cf, checkFixture, copyFixture, type JsonReport, readIndexes, realTemplates, vaultFlags } from "./helpers.ts";

const NOTE = "%% Generated by `cf index`. Never edit by hand. %%";

const ROOT_INDEX = `${NOTE}

# Wiki

- [[Ashes of the Crown|Ashes of the Crown]] — Four friends chase the last flame of the Crown.
`;

const CAMPAIGN_INDEX = `${NOTE}

# Ashes of the Crown

## Locations

### Regions

- [[Ashen Reach|Ashen Reach]] — Burnt hills north of the river.

### Settlements

- [[Ravenhold|Ravenhold]] — A walled river port that taxes every barge.

### Sites

- [[The Sunken Chapel|The Sunken Chapel]] — A flooded chapel under the river wall.

## NPCs

- [[morrow|Captain Morrow]] — One line.
- [[Mara Voss|Mara Voss]] — Harbormaster with a bandit's past.

## Creatures

- [[Bandit Captain|Bandit Captain]] — A veteran raider who leads from the front.

## Factions

- [[Ember Court|Ember Court]] — Nobles who guard the memory of the Crown.

## Deities

- [[Orsa|Orsa]] — Goddess of hearths and second chances.

## Items

- [[Ashen Lantern|Ashen Lantern]] — A lantern that shows what burned.

## Spells

- [[Cinder Ward|Cinder Ward]] — A ward of drifting embers.

## Vehicles

- [[Gull's Errand|Gull's Errand]] — A river barge with a patched sail.

## Lore

- [[Crown Fire|Crown Fire]] — How the Crown burned in a single night.

## House Rules

- [[Fire Watch|Fire Watch]] — Anyone on watch may roll a Wisdom save to wake.
- [[Old Crossing Rules|Old Crossing Rules]] — Crossing the bridge at Ravenhold costs a toll roll.

## Worlds

- [[Aldermoor|Aldermoor]] — A river country on the edge of the Ashen Reach.

## PCs

- [[Tam Brightwater|Tam Brightwater]] — A ferry pilot with a borrowed name.

## Threads

- [[The Cold Hearth|The Cold Hearth]] — Mara's hearth is failing, and so is her hold.

## Quests

- [[Lantern for the Chapel|Lantern for the Chapel]] — Bring the Ashen Lantern out of the chapel.

## Preps

- [[Session 1 - Prep|Session 1 - Prep]] — A storm pins the Party at the bridge.

## Scenes

- [[Session 1 - Storm at the Crossing|Session 1 - Storm at the Crossing]] — A storm pins the Party at the bridge.

## Recaps

- [[Session 1 - Recap|Session 1 - Recap]] — The Party crossed the bridge and met Mara Voss.

## Previously On

- [[Session 2 - Previously On|Session 2 - Previously On]] — Last time the Party crossed the bridge.

## Handouts

- [[Wanted Poster|Wanted Poster]] — A poster for the Bandit Captain.
`;

/** A copy of the clean fixture with its generated indexes deleted. */
async function unindexed(): Promise<string> {
	const dir = await copyFixture("clean");
	await rm(join(dir, "wiki/index.md"));
	await rm(join(dir, "wiki/ashes-of-the-crown/index.md"));
	return dir;
}

const npcPage = (title: string, summary: string) => `---\ntype: NPC\ntitle: "${title}"\nsummary: "${summary}"\nsources: []\ncreature: ""\n---\n\n## At a glance\n\nSee [[Mara Voss|Mara Voss]].\n`;

describe("cf index", () => {
	it("generates the root and Campaign-folder indexes from every summary, grouped by page kind", async () => {
		const dir = await unindexed();
		const { code, stdout } = await cf(["index", ...vaultFlags(dir)], dir);
		expect(code).toBe(0);
		expect(stdout).toMatch(/^wrote {2}wiki\/index\.md$/m);
		expect(stdout).toMatch(/^wrote {2}wiki\/ashes-of-the-crown\/index\.md$/m);
		const indexes = await readIndexes(dir);
		expect(indexes.get("wiki/index.md")).toBe(ROOT_INDEX);
		expect(indexes.get("wiki/ashes-of-the-crown/index.md")).toBe(CAMPAIGN_INDEX);
	});

	it("is byte-identical on a re-run and reports nothing to change", async () => {
		const dir = await unindexed();
		await cf(["index", ...vaultFlags(dir)], dir);
		const before = await readIndexes(dir);
		const again = await cf(["index", ...vaultFlags(dir)], dir);
		expect(again.code).toBe(0);
		expect(again.stdout).toContain("up to date");
		expect(again.stdout).not.toMatch(/^wrote /m);
		expect(await readIndexes(dir)).toEqual(before);
	});

	it("matches the generated index files committed in the clean fixture", async () => {
		const dir = await unindexed();
		await cf(["index", ...vaultFlags(dir)], dir);
		const committed = await copyFixture("clean");
		expect(await readIndexes(dir)).toEqual(await readIndexes(committed));
	});

	it("prints a slug-filename page under its title", async () => {
		const text = (await readIndexes(await copyFixture("clean"))).get("wiki/ashes-of-the-crown/index.md")!; // morrow.md carries `title: Captain Morrow`
		expect(text).toContain("- [[morrow|Captain Morrow]] — One line.");
		expect(text).not.toContain("- [[morrow]]");
	});

	it("changing one summary changes exactly one line", async () => {
		const dir = await unindexed();
		await cf(["index", ...vaultFlags(dir)], dir);
		const before = (await readIndexes(dir)).get("wiki/ashes-of-the-crown/index.md")!.split("\n");
		const page = join(dir, "wiki/ashes-of-the-crown/NPCs/Mara Voss.md");
		await writeFile(page, (await readFile(page, "utf8")).replace("Harbormaster with a bandit's past.", "Harbormaster and secret smuggler."));
		await cf(["index", ...vaultFlags(dir)], dir);
		const after = (await readIndexes(dir)).get("wiki/ashes-of-the-crown/index.md")!.split("\n");
		expect(after).toHaveLength(before.length);
		const changed = after.filter((line, i) => line !== before[i]);
		expect(changed).toEqual(["- [[Mara Voss|Mara Voss]] — Harbormaster and secret smuggler."]);
	});

	it("sorts pages by name within a group, numbers by value, independent of locale", async () => {
		const dir = await unindexed();
		const npcs = join(dir, "wiki/ashes-of-the-crown/NPCs");
		for (const name of ["Zed", "apple", "Édith", "Guard 10", "Guard 2"]) await writeFile(join(npcs, `${name}.md`), npcPage(name, `About ${name}.`));
		await cf(["index", ...vaultFlags(dir)], dir);
		const text = (await readIndexes(dir)).get("wiki/ashes-of-the-crown/index.md")!;
		const npcLines = text.split("\n## NPCs\n\n")[1]!.split("\n\n")[0]!.split("\n");
		expect(npcLines.map((l) => l.replace(/^- \[\[.*?\|(.*?)\]\].*$/, "$1"))).toEqual(["Captain Morrow", "Guard 2", "Guard 10", "Mara Voss", "Zed", "apple", "Édith"]);
	});

	it("--dry-run prints what would change and writes nothing", async () => {
		const dir = await unindexed();
		const { code, stdout } = await cf(["index", "--dry-run", ...vaultFlags(dir)], dir);
		expect(code).toBe(0);
		expect(stdout).toMatch(/^would write {2}wiki\/index\.md$/m);
		expect(stdout).toMatch(/^would write {2}wiki\/ashes-of-the-crown\/index\.md$/m);
		await expect(readFile(join(dir, "wiki/index.md"), "utf8")).rejects.toThrow();
	});

	it("documents itself in --help, with examples", async () => {
		const { code, stdout } = await cf(["index", "--help"]);
		expect(code).toBe(0);
		for (const option of ["--vault", "--root", "--dry-run"]) expect(stdout).toContain(option);
		expect(stdout).toContain("Examples:");
		expect(stdout).toMatch(/^ {2}cf index$/m);
		expect(stdout).toMatch(/^ {2}cf index --dry-run$/m);
		expect(stdout).toContain("Exit codes:");
	});

	it("exits 2 with an example when the vault folder is missing", async () => {
		const { code, stderr } = await cf(["index", "--vault", "/no/such/folder"]);
		expect(code).toBe(2);
		expect(stderr).toContain("cf index --vault <folder>");
	});
});

describe("index layer", () => {
	const gate = async (dir: string, extra: string[] = []) => {
		const result = await cf(["check", "--json", "--layer", "index", ...vaultFlags(dir), "--templates", realTemplates, ...extra], dir);
		return { ...result, report: JSON.parse(result.stdout) as JsonReport };
	};

	it("passes the committed indexes of the clean fixture", async () => {
		const { report, code } = await checkFixture("clean", ["--layer", "index"]);
		expect(code).toBe(0);
		expect(report.findings).toEqual([]);
	});

	it("flags a missing index.md, root and Campaign folder", async () => {
		const { report, code } = await gate(await unindexed());
		expect(code).toBe(1);
		expect(report.findings.map((f) => [f.path, f.rule])).toEqual([
			["wiki/ashes-of-the-crown/index.md", "missing"],
			["wiki/index.md", "missing"],
		]);
		expect(report.findings[0]!.hint).toContain("cf index");
	});

	it("flags a stale index, on the first line that differs", async () => {
		const dir = await copyFixture("clean");
		const page = join(dir, "wiki/ashes-of-the-crown/NPCs/Mara Voss.md");
		await writeFile(page, (await readFile(page, "utf8")).replace("Harbormaster with a bandit's past.", "Harbormaster and secret smuggler."));
		const { report } = await gate(dir);
		expect(report.findings).toHaveLength(1);
		const [finding] = report.findings;
		expect(finding).toMatchObject({ path: "wiki/ashes-of-the-crown/index.md", rule: "stale" });
		const lines = (await readFile(join(dir, "wiki/ashes-of-the-crown/index.md"), "utf8")).split("\n");
		expect(lines[finding!.line - 1]).toBe("- [[Mara Voss|Mara Voss]] — Harbormaster with a bandit's past.");
		expect(finding!.hint).toContain("cf index");
	});

	it("flags an index someone edited by hand", async () => {
		const dir = await copyFixture("clean");
		const path = join(dir, "wiki/index.md");
		await writeFile(path, `${await readFile(path, "utf8")}\n- [[Nowhere|Nowhere]] — Added by hand.\n`);
		const { report } = await gate(dir);
		expect(report.findings.map((f) => [f.path, f.rule])).toEqual([["wiki/index.md", "stale"]]);
	});

	it("flags a page added since the index was generated", async () => {
		const dir = await copyFixture("clean");
		await writeFile(join(dir, "wiki/ashes-of-the-crown/NPCs/Newcomer.md"), npcPage("Newcomer", "Just arrived."));
		const { report } = await gate(dir);
		expect(report.findings.map((f) => [f.path, f.rule])).toEqual([["wiki/ashes-of-the-crown/index.md", "stale"]]);
	});

	it("--fix regenerates missing and stale indexes, and a re-check is clean", async () => {
		const dir = await unindexed();
		await writeFile(join(dir, "wiki/ashes-of-the-crown/NPCs/Newcomer.md"), npcPage("Newcomer", "Just arrived."));
		const fixed = await gate(dir, ["--fix"]);
		expect(fixed.report.fixes.map((f) => [f.path, f.rule])).toEqual([
			["wiki/ashes-of-the-crown/index.md", "missing"],
			["wiki/index.md", "missing"],
		]);
		expect(fixed.report.findings).toEqual([]);
		expect((await readIndexes(dir)).get("wiki/ashes-of-the-crown/index.md")).toContain("- [[Newcomer|Newcomer]] — Just arrived.");
		const again = await gate(dir, ["--fix"]);
		expect(again.report.fixes).toEqual([]);
		expect(again.code).toBe(0);
	});

	it("--fix --dry-run reports the fix and writes nothing", async () => {
		const dir = await unindexed();
		const { report } = await gate(dir, ["--fix", "--dry-run"]);
		expect(report.fixes).toHaveLength(2);
		await expect(readFile(join(dir, "wiki/index.md"), "utf8")).rejects.toThrow();
	});
});
